<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.crysknife.tests</groupId>
    <artifactId>reduces-classpath-dep</artifactId>
    <version>0.11</version>
    <packaging>jar</packaging>

    <name>Crysknife :: Tests :: JRE :: Reduced Classpath :: Dep</name>
    <description>Reduced classpath test dependency</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.deploy.skip>true</maven.deploy.skip>
        <gwt.jakarta.version>0.7</gwt.jakarta.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.treblereel.gwt.jakarta</groupId>
                <artifactId>bom</artifactId>
                <version>${gwt.jakarta.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.treblereel.gwt.jakarta</groupId>
            <artifactId>cdi</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
